[package]
name = "toy"
version = "0.1.0"
authors = ["jiawei <934628017@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "0.9.0"
bson = "0.14.0"
serde = "1.0.104"